#!/usr/bin/env python3
"""The deployment generator (task #11, docs/design.md section 2).

    python3 scripts/generate.py deploy/example.toml            # write generated/deploy.ls
    python3 scripts/generate.py deploy/example.toml --check    # change nothing; exit 1 if it is stale
    python3 scripts/generate.py deploy/example.toml --explain  # print what it admits, change nothing

Every refusal is a rule tag, a message, and exit code 2 (a refused deployment is not a stale file).
"""

import pathlib
import re
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "generated" / "deploy.ls"
MAX_UPSTREAMS = 256


class Refusal(Exception):
    def __init__(self, rule, message):
        super().__init__(message)
        self.rule = rule


def host_port(addr):
    m = re.fullmatch(r"([A-Za-z0-9.-]+):([0-9]{1,5})", addr)
    if not m or not 1 <= int(m.group(2)) <= 65535 or m.group(1).startswith((".", "-")):
        raise Refusal("config.upstream", "upstream address %r is not host:port with a port in 1..65535" % addr)
    return m.group(1), int(m.group(2))


def intended_prefix(addrs):
    """The longest common prefix of the addresses, cut back to the last '.' or ':' so that it cannot
    admit a host the addresses do not (10.0.1.5 and 10.0.1.50 share '10.0.1.5', which would admit
    10.0.1.5x). A single upstream is its full host:port. The empty string means no shared prefix."""
    if len(addrs) == 1:
        return addrs[0]
    common = addrs[0]
    for a in addrs[1:]:
        n = 0
        while n < min(len(common), len(a)) and common[n] == a[n]:
            n += 1
        common = common[:n]
    cut = max(common.rfind("."), common.rfind(":"))
    return common[:cut + 1] if cut >= 0 else ""


def load(path):
    try:
        with open(path, "rb") as f:
            doc = tomllib.load(f)
    except (OSError, tomllib.TOMLDecodeError) as e:
        raise Refusal("config.read", "cannot read %s: %s" % (path, e))
    listen = doc.get("listen")
    if not isinstance(listen, int) or isinstance(listen, bool) or not 1 <= listen <= 65535:
        raise Refusal("config.listen", "listen must be a port in 1..65535")
    ups = doc.get("upstream", [])
    if not ups:
        raise Refusal("config.upstream", "at least one [[upstream]] is required")
    if len(ups) > MAX_UPSTREAMS:
        raise Refusal("config.count", "%d upstreams; the bound is %d" % (len(ups), MAX_UPSTREAMS))
    names, addrs = set(), []
    for u in ups:
        name, addr = u.get("name"), u.get("addr")
        if not isinstance(name, str) or not re.fullmatch(r"[a-z][a-z0-9_-]{0,31}", name):
            raise Refusal("config.upstream", "upstream name %r must match [a-z][a-z0-9_-]{0,31}" % (name,))
        if not isinstance(addr, str):
            raise Refusal("config.upstream", "upstream %s has no addr" % name)
        host_port(addr)
        if name in names or addr in addrs:
            raise Refusal("config.duplicate", "upstream %s or address %s is listed twice" % (name, addr))
        names.add(name)
        addrs.append(addr)
    return listen, [(u["name"], u["addr"]) for u in ups]


def literal(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(listen, ups):
    addrs = [a for _, a in ups]
    prefix = intended_prefix(addrs)
    lines = [
        "edition 5;", "", "module gateway.deploy;", "",
        "// Generated by scripts/generate.py from a deployment file -- do not edit (docs/design.md section 2).",
        "// The allowed upstreams are data compiled into the binary; the compiler's authority report cannot see",
        "// them (one Net, one bound shared by listen and connect: design section 2.1), so the gateway enforces",
        "// this list in code before every connect and `authority.toml` states the report is `net_out(\"\")`.", "",
        "pub fn listen_port() -> [] int {", "    return %d;" % listen, "}", "",
        "pub fn upstream_count() -> [] int {", "    return %d;" % len(ups), "}", "",
        "// The longest common prefix of the addresses, cut at a delimiter: what `narrow` would be given once",
        "// lex-sys has separate listen and connect bounds. Empty means no shared prefix.",
        "pub fn intended_egress_prefix() -> [] &static [byte] {", "    return %s;" % literal(prefix), "}", "",
        "// Upstream `i` (0-based), as host:port; the empty string past the end.",
        "pub fn upstream_addr(i: int) -> [] &static [byte] {",
    ]
    for i, (_, a) in enumerate(ups):
        lines += ["    if i == %d {" % i, "        return %s;" % literal(a), "    }"]
    lines += ['    return "";', "}", "", "pub fn upstream_name(i: int) -> [] &static [byte] {"]
    for i, (n, _) in enumerate(ups):
        lines += ["    if i == %d {" % i, "        return %s;" % literal(n), "    }"]
    lines += ['    return "";', "}", ""]
    return "\n".join(lines)


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    flags = {a for a in sys.argv[1:] if a.startswith("--")}
    if len(args) != 1:
        print("usage: generate.py DEPLOYMENT.toml [--check|--explain]", file=sys.stderr)
        return 2
    try:
        listen, ups = load(args[0])
    except Refusal as r:
        print('{"rule":"%s","message":%s}' % (r.rule, literal(str(r))), file=sys.stderr)
        return 2
    text = render(listen, ups)
    if "--explain" in flags:
        prefix = intended_prefix([a for _, a in ups])
        print("listen %d; %d upstream(s): %s" % (listen, len(ups), ", ".join(a for _, a in ups)))
        print("intended egress prefix: %s" % (repr(prefix) if prefix else "none (no shared prefix)"))
        return 0
    if "--check" in flags:
        if not OUT.exists() or OUT.read_text() != text:
            print("FAIL %s is stale: run scripts/generate.py %s" % (OUT.relative_to(ROOT), args[0]))
            return 1
        return 0
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
